[package]
name = "xcfc"
version = "0.1.0"
edition = "2021"

[lib]
name = "xcfc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
ndarray = "0.15"
ndarray-stats = "0.6"
rand = "0.8"
